import LayoutWithoutSidebar from "../layout/LayoutWithoutSidebar/LayoutWithoutSidebar";
import "./../globals.css";
import { Suspense } from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="custom-scroll font-sans">
        <Suspense>
          <LayoutWithoutSidebar>{children}</LayoutWithoutSidebar>
        </Suspense>
      </body>
    </html>
  );
}
