import LayoutWithoutSidebar from "../layout/LayoutWithoutSidebar/LayoutWithoutSidebar"
import './../globals.css'
import StoreProvider from "../StoreProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children,}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="custom-scroll">
        <StoreProvider>
          <LayoutWithoutSidebar>
            {children}
          </LayoutWithoutSidebar>
        </StoreProvider>
      </body>
    </html>
  )
}
