import type { Metadata } from "next";
import "./globals.css";
import { SimpleLayout } from "./layout/SimpleLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
        <SimpleLayout>
          {children}
        </SimpleLayout>
      </body>
    </html>
  );
}
