
import type { Metadata } from "next";
import "../globals.css";
import { SimpleLayout } from "../layout/SimpleLayout";
import StoreProvider from "../StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className=" lg:overflow-hidden">
        <StoreProvider>
          <SimpleLayout>
              {children}
          </SimpleLayout>
        </StoreProvider>
      </body>
    </html>
  );
}
