import type { Metadata } from "next";
import { Suspense } from "react";
import "../globals.css";
import { SimpleLayout } from "../layout/SimpleLayout";
import StoreProvider from "../StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className=" lg:overflow-hidden">
        <Suspense>
          <StoreProvider>
            <SimpleLayout>{children}</SimpleLayout>
          </StoreProvider>
        </Suspense>
      </body>
    </html>
  );
}
